name: CPQ Auto Renewal Email

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
#==========================================================Dev(T2)==================================================

  Trigger-Email-Action-Invoke:
    #if: contains(github.ref, 'release') || github.event.inputs.Environment == 'Dev(T2)'
    runs-on: ubuntu-latest
    environment: eatontest2(dev)

    steps:
     - name: Get result data
       run: |
         curl -X POST \
          -u ${{ 'E0623429' }}:${{ 'Test@123' }} \
          -H "Content-Type:application/json" \
          ${{ vars.EATONTEST2_URL }}/rest/v14/commerceDocumentsOraclecpqoTransaction/2080946060/actions/autoRenewalTransaction_c > getresponse.json
         echo \n ========= This is Json output=======
         cat getresponse.json
         result=`cat  getresponse.json | jq -r '.result'`
         echo $result
         echo "result=$result" >> $GITHUB_ENV
    outputs:
      result: ${{ env.result }}
